---
swagger: '2.0'
info:
  title: Setup Endpoints
  description: Setup Endpoints
  contact:
    url: https://ibm-cloudplatform.slack.com/archives/devops-dev-desktop
  version: 1.0.0
host: otc-ui.us-south.devops.dev.cloud.ibm.com
schemes:
- https
basePath: /devops/setup
consumes:
- application/json
produces:
- application/json
paths:
  /api/v2/template/repo/{repo_url}:
    get:
      tags:
      - api/v2
      parameters:
      - in: path
        name: repo_url
        type: string
        required: true
      responses:
        '200' :
          description: '' 
    post:
      tags:
      - api/v2
      parameters:
      - in: path
        name: repo_url
        type: string
        required: true
      responses:
        '200' :
          description: '' 
  /api/v2/template/app/{region_id}/{app_guid}:
    get:
      tags:
      - api/v2
      parameters:
      - in: path
        name: region_id
        type: string
        required: true
      - in: path
        name: app_guid
        type: string
        required: true
      responses:
        '200' :
          description: '' 
  /api/v2/template/zip/{zip_url}:
    get:
      tags:
      - api/v2
      parameters:
      - in: path
        name: zip_url
        type: string
        required: true
      responses:
        '200' :
          description: '' 

  /api/v2/template-ui/repo/{repo_url}:
    get:
      tags:
      - api/v2
      parameters:
      - in: path
        name: repo_url
        type: string
        required: true
      responses:
        '200' :
          description: '' 
    post:
      tags:
      - api/v2
      parameters:
      - in: path
        name: repo_url
        type: string
        required: true
      responses:
        '200' :
          description: '' 
  /api/v2/template-ui/app/{region_id}/{app_guid}:
    get:
      tags:
      - api/v2
      parameters:
      - in: path
        name: region_id
        type: string
        required: true
      - in: path
        name: app_guid
        type: string
        required: true
      responses:
        '200' :
          description: '' 
  /api/v2/template-ui/zip/{zip_url}:
    get:
      tags:
      - api/v2
      parameters:
      - in: path
        name: zip_url
        type: string
        required: true
      responses:
        '200' :
          description: '' 

  /api/v2/toolchains:
    get:
      tags:
      - api/v2
      responses:
        '200' :
          description: '' 
    post:
      tags:
      - api/v2
      responses:
        '200' :
          description: '' 

  /api/v2/resource_groups:
    get:
      tags:
      - api/v2
      responses:
        '200' :
          description: '' 

  /api/v2/apiKeys:
    post:
      tags:
      - api/v2
      responses:
        '200' :
          description: ''

  /api/v2/serviceIds:
    post:
      tags:
      - api/v2
      responses:
        '200' :
          description: ''

  /api/v2/serviceIdApiKeyDetail:
    post:
      tags:
      - api/v2
      responses:
        '200' :
          description: '' 

  /api/v2/regions/:
    get:
      tags:
      - api/v2
      responses:
        '200' :
          description: '' 

  /api/toolchains:
    get:
      tags:
      - api
      responses:
        '200' :
          description: '' 

  /validator/v1/validate:
    post:
      tags:
      - validator/v1
      responses:
        '200' :
          description: '' 
  /validator/v1/populate:
    post:
      tags:
      - validator/v1
      responses:
        '200' :
          description: '' 